name: Deploy

on:
  workflow_run:
    workflows: ["Build"] 
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Read image tag
        id: tag
        run: echo "TAG=$(cat image-tag.txt)" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions
            manifest.yaml
          sparse-checkout-cone-mode: false

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Container App
        uses: ./.github/actions/deploy/container
        with:
          resourceGroupName: ${{ vars.AZURE_RESOURCE_GROUP }}
          containerAppName: patient-onboarding
          manifestFilePath: ./manifest.yaml
          overwriteManifest: true
          customDomain: ${{ vars.ONBOARDING_APP_DOMAIN || ''}}
          environmentUri: ${{ vars.AZURE_ENVIRONMENT_ID }}
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
